# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >


 language: python
 cache:
     directories:
         - "~/.platformio"
      
 env:
     - PLATFORMIO_CI_SRC=src/main.cpp

 install:
     #platform IO (AVR)
     - pip install -U platformio
     - platformio update

     # include for Servo motor driver 
     - wget https://github.com/pololu/maestro-arduino/archive/master.zip -O /tmp/maestro-arduino-master.zip
     - unzip /tmp/maestro-arduino-master.zip -d /tmp/

     # include for Steppermoter chip driver
     - wget https://github.com/interactive-matter/TMC26XStepper/archive/master.zip -O /tmp/TMC26XStepper-master.zip
     - unzip /tmp/TMC26XStepper-master.zip -d /tmp/

     #include for Encoder Sensor (steppermotor)
     - wget https://github.com/PaulStoffregen/Encoder/archive/master.zip -O /tmp/Encoder-master.zip
     - unzip /tmp/Encoder-master.zip -d /tmp/

 script:
     - platformio ci --lib="." --lib="./lib/GPIO/src" --lib="./include/MotorControl"  --lib="/tmp/Encoder-master" --lib="/tmp/TMC26XStepper-master" --lib="/tmp/maestro-arduino-master" --board=uno
     