# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#
#
# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#install:
#    - pip install -U platformio
#     - platformio update
#
# script:
#     - platformio run


#
# Template #2: The project is intended to be used as a library with examples.
#

 language: python
 cache:
     directories:
 
        - "~/.platformio"
 env:
     - PLATFORMIO_CI_SRC=src/main.cpp

 install:
     - pip install -U platformio
     - platformio update

     - wget https://github.com/pololu/maestro-arduino/archive/master.zip -O /tmp/maestro-arduino-master.zip
     - unzip /tmp/maestro-arduino-master.zip -d /tmp/

     - wget https://github.com/interactive-matter/TMC26XStepper/archive/master.zip -O /tmp/TMC26XStepper-master.zip
     - unzip /tmp/TMC26XStepper-master.zip -d /tmp/

     - wget https://github.com/PaulStoffregen/Encoder/archive/master.zip -O /tmp/Encoder-master.zip
     - unzip /tmp/Encoder-master.zip -d /tmp/


     #     - PLATFORMIO_CI_SRC=src/main.cpp
     # - PLATFORMIO_CI_SRC=lib/GPIO/src
     # - PLATFORMIO_CI_SRC=include/Motorcontrol
     #- PLATFORMIO_CI_SRC= ./
 script:
     - platformio ci --lib="."  --lib=/tmp/Encoder-master.zip" --lib="/tmp/TMC26XStepper-master.zip" --lib="/tmp/maestro-arduino-master.zip"--board=uno
